import { Container, Start } from './styles';
import { Layout } from '@/components/newlayout';
import Head from 'next/head';
import Image from 'next/image';
import { ChatCenteredDots } from 'phosphor-react';
import { Poppins } from '@next/font/google';
const poppins = Poppins({
  weight: ['100', '200', '300', '300', '500', '600', '700', '800', '900'],
  subsets: ['latin', 'devanagari', 'latin-ext'],
  preload: true,
});

interface IPropsLayout{
  children: React.ReactNode
}

export  function SigninLayout({children}:IPropsLayout) {
  return (
    <>
      <Head>
        <title>WebChat | Sing In</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <Layout
        centralizedComponents={true}
        classname={poppins.className}
      >
        <Container>
          <Start>
            <h1>
              <Image
                src="/welcome.svg"
                alt="Ícone de uma mão amarela dando olá"
                width={50}
                height={50}
                placeholder="blur"
                blurDataURL="/welcome.svg"
              />
              Bem vindo ao WebChat!
            </h1>

            <p>
              Conheça novas pessoas e troque mensagens com amigos em tempo real
              <ChatCenteredDots />
            </p>
            <span></span>
          </Start>
          {children}
        </Container>
      </Layout>
    </>
  );
}
